"""S1.1 -- width/depth scaling sweep, GT-only.

The plan's question: is CAPACITY the binding constraint, or is the remaining gap
training protocol / multi-task dilution? Success is monotone improvement with the
teacher gap visibly shrinking; the kill is PSNR saturating before the gap closes.

The corrected evaluation sharpened what this is testing. Two of the three gaps
are already effectively closed (dehaze 0.328 dB, denoise 0.460); only DERAIN is
open, at 3.482 dB. So S1.1 is now specifically asking whether scale closes a
derain gap that the plan itself predicts scaling buys only ~0.3-0.5 dB against.
A kill here is a real result, not a disappointment.

Sizes are the plan's own budget table, and the configuration behind each number
was recovered by matching parameter counts exactly rather than assumed:

    w16        7,447,331   already trained as B0V3 (GT-only, 90k) -- the anchor
    w16-deeper 14,469,731  enc [4,4,8,16], middle 24, dec [4,4,4,4]
    w24       16,632,387   enc [2,2,4,8],  middle 12, dec [2,2,2,2]
    w32       29,458,371   enc [2,2,4,8],  middle 12, dec [2,2,2,2]

"deeper" = every block count doubled; that reproduces 14,469,731 to the digit.
NOTE: the plan lists w24-deeper as 24,471,603, which this scheme does NOT
reproduce (it gives 32,310,819). That row's configuration is unrecovered, so
w24-deeper is deliberately NOT generated here rather than guessed at.

Every arm is identical to B0V3 apart from width/depth -- same GT-only regime,
same data, same 90k cosine schedule, same seed -- so the sweep moves one
variable. Cost order follows the plan's steer that depth beats width per
parameter (Cho & Hariharan), so w16-deeper runs first.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BASE = Path("configs/train/b0v3.yaml")   # the GT-only w16 anchor

DEEP = dict(enc="[4, 4, 8, 16]", mid=24, dec="[4, 4, 4, 4]")
FLAT = dict(enc="[2, 2, 4, 8]", mid=12, dec="[2, 2, 2, 2]")

ARMS = {
    "S11-W16-DEEP": dict(cfg="configs/train/s11_w16_deep.yaml", width=16, **DEEP,
                         params="14,469,731",
                         desc="S1.1 scaling: w16 DEEPER (blocks doubled), GT-only"),
    "S11-W24": dict(cfg="configs/train/s11_w24.yaml", width=24, **FLAT,
                    params="16,632,387",
                    desc="S1.1 scaling: w24, GT-only"),
    "S11-W32": dict(cfg="configs/train/s11_w32.yaml", width=32, **FLAT,
                    params="29,458,371",
                    desc="S1.1 scaling: w32, GT-only"),
}


def main() -> int:
    base = BASE.read_text(encoding="utf-8")
    if "arch:" not in base:
        raise SystemExit(f"{BASE} has no arch: section")

    for arm, s in ARMS.items():
        txt = base
        m = re.search(r"(?m)^arch:\n((?:[ \t].*\n)*)", txt)
        if not m:
            raise SystemExit("could not locate arch: section")
        block = m.group(1)
        block = re.sub(r"(?m)^  width:.*$", f"  width: {s['width']}", block)
        block = re.sub(r"(?m)^  enc_blk_nums:.*$", f"  enc_blk_nums: {s['enc']}", block)
        block = re.sub(r"(?m)^  middle_blk_num:.*$", f"  middle_blk_num: {s['mid']}", block)
        block = re.sub(r"(?m)^  dec_blk_nums:.*$", f"  dec_blk_nums: {s['dec']}", block)
        txt = txt[:m.start(1)] + block + txt[m.end(1):]
        txt = (f"# S1.1 scaling arm, generated by scripts/make_s11_arms.py.\n"
               f"# {s['desc']}  ({s['params']} params)\n"
               f"# Identical to b0v3.yaml except width/depth -- GT-only, same data,\n"
               f"# same 90k cosine schedule, same seed.\n" + txt)
        Path(s["cfg"]).write_text(txt, encoding="utf-8")
        print(f"wrote {s['cfg']}")

    tp = Path("src/train/train.py")
    src = tp.read_text(encoding="utf-8")
    if "S11-W16-DEEP" in src:
        print("arms already registered")
        return 0
    anchor = '    "B0V3M": {"norm": {"arch": "student_v3",'
    if src.count(anchor) != 1:
        raise SystemExit("ARMS anchor not unique")
    entries = []
    for arm, s in ARMS.items():
        entries.append(
            f'    # {s["desc"]} ({s["params"]} params)\n'
            f'    "{arm}": {{"norm": {{"arch": "student_v3",\n'
            f'                 "width": {s["width"]},\n'
            f'                 "enc_blk_nums": {s["enc"]},\n'
            f'                 "middle_blk_num": {s["mid"]},\n'
            f'                 "dec_blk_nums": {s["dec"]},\n'
            f'                 "use_dcp_prior": True,\n'
            f'                 "use_strip_pool": True,\n'
            f'                 "use_oriented_streak": True,\n'
            f'                 "norm_type": "layernorm2d",\n'
            f'                 "full_res_norm_type": "affine_clamp",\n'
            f'                 "clamp_bound": 8.0,\n'
            f'                 "enc_clamp_stages": [3], "deep_clamp_bound": 32.0}},\n'
            f'              "config": "{s["cfg"]}",\n'
            f'              "desc": "{s["desc"]}"}},\n')
    src = src.replace(anchor, "".join(entries) + anchor)

    geo = '                "B0V3M": W16_SIDD,'
    if src.count(geo) != 1:
        raise SystemExit("ARM_GEOMETRY anchor not unique")
    src = src.replace(geo, "".join(f'                "{a}": W16_SIDD,\n'
                                   for a in ARMS) + geo)
    tp.write_text(src, encoding="utf-8")
    print(f"registered {len(ARMS)} arms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
