"""DERAIN-ONLY-W16 — does three-task dilution explain the derain gap?

Derain is the ONLY open gap (3.482 dB vs teacher). Dehaze (0.328) and denoise
(0.460) are effectively closed. Three candidate causes remain for derain:
capacity, schedule length, and three-task dilution. This arm isolates the third.

  FIXED   StudentV3 w16, 7,447,331 params  (identical to B0V3)
          90k cosine, warmup 3k, min_lr 1e-6
          GT-only, no KD
          eval BSD68 / Rain100L-100 / SOTS-clean
  VARIED  task set: three tasks -> derain alone
  CONTROL B0V3 (StudentV3, GT-only, 3-task, 90k), derain 35.547 re-scored

GT-only is deliberate on two counts: it matches B0V3 so the comparison moves one
variable, and KD is MEASURED at -0.388 dB on derain, so including it would push
the task under study in the harmful direction.

THE CONFOUND, stated up front rather than discovered in the result.
`MixedTaskDataset` gives every task an exactly equal share -- stream_length is
`length // n_tasks`, independent of how many files a task owns (build.py:380-385,
and the class docstring says so explicitly; the x120 multiplier mentioned in the
module header is AdaIR's scheme, which this repo deliberately does NOT use). So
the exposure ratio is a clean 3:1: over 90k x batch 16 this arm sees the 200
RainTrainL pairs ~7,200 times against the 3-task run's ~2,400.

That means "dilution" and "loss of cross-task regularisation" are entangled. If
the specialist LOSES, that may be overfitting to 200 images rather than evidence
against dilution. Train loss and held-out PSNR are both already in history.json
per checkpoint, so divergence identifies overfitting directly rather than leaving
it to interpretation.

An epoch-matched variant would remove the confound but changes the schedule --
trading a clean variable for a dirty one. Not taken.

FRAMING THAT NARROWS THE CONCLUSION. AdaIR trains derain on the SAME Rain100L 200
pairs and reaches 38.641 against our 35.547. Same images, same count. Data volume
therefore cannot explain the teacher-student gap, and "we need more rain data" is
refuted before this runs. A positive result here is unambiguously about capacity
ALLOCATION, not data.

READING THE RESULT (agreed with the analysis session before running):
  >= +1.0 dB   dilution is a major cause; task-conditioning / task-specific heads
               become the lever, not more parameters.
  +0.1..+0.9   dilution is REAL but MINOR -- contributes without explaining the
               3.482. Worth trying conditioning; do NOT redirect the project on
               this alone. Capacity and schedule stay live.
  within 0.07  EITHER dilution is not the cause, OR dilution and lost cross-task
               regularisation cancel. Separate them with the train-loss trace: if
               the specialist's train loss falls faster while val PSNR matches,
               it is cancellation, not absence.
  << control   overfitting to 200 images dominates (confirm via train/val
               divergence). The binding constraint would be derain DATA -- but
               see the framing above, which makes this unlikely to explain the
               teacher gap.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BASE = Path("configs/train/b0v3.yaml")          # GT-only w16, the control
OUT = Path("configs/train/derain_only_w16.yaml")
ARM = "DERAIN-ONLY-W16"
DESC = ("Single-task derain, StudentV3 w16, GT-only -- isolates three-task "
        "dilution (control: B0V3)")


def main() -> int:
    txt = BASE.read_text(encoding="utf-8")

    m = re.search(r"(?m)^data:\n((?:[ \t].*\n|\n)*?)(?=^[a-z_]+:)", txt)
    if not m:
        raise SystemExit("could not locate the data: block")
    block = m.group(1)

    # replace the whole tasks: mapping with derain alone
    new_tasks = "  tasks:\n    derain: Train/Derain\n"
    # no `s` flag: with DOTALL, `.` matches newlines and `    .*` swallows
    # the rest of the block -- that silently dropped num_workers and
    # cache_budget_gb, making the arm differ in THREE ways, not one.
    block2 = re.sub(r"(?m)^  tasks:\n(?:    .*\n)+", new_tasks, block)
    if block2 == block:
        raise SystemExit("tasks: mapping not replaced -- check the config shape")
    txt = txt[:m.start(1)] + block2 + txt[m.end(1):]

    header = (f"# {ARM} -- {DESC}\n"
              f"# Generated by scripts/make_derain_arm.py from {BASE}.\n"
              f"# IDENTICAL to b0v3.yaml except data.tasks: three tasks -> derain\n"
              f"# alone. Same arch, same 90k schedule, same GT-only regime, same\n"
              f"# leak-free eval sets. See the script docstring for the confound\n"
              f"# (3:1 exposure ratio) and the agreed reading of each outcome.\n")
    OUT.write_text(header + txt, encoding="utf-8")
    print(f"wrote {OUT}")

    tp = Path("src/train/train.py")
    src = tp.read_text(encoding="utf-8")
    if ARM in src:
        print("arm already registered")
        return 0
    anchor = '    "B0V3": {"norm": {"arch": "student_v3",'
    if src.count(anchor) != 1:
        raise SystemExit(f"ARMS anchor matched {src.count(anchor)} times")
    entry = (f'    # {DESC}\n'
             f'    "{ARM}": {{"norm": {{"arch": "student_v3",\n'
             f'                 "use_dcp_prior": True,\n'
             f'                 "use_strip_pool": True,\n'
             f'                 "use_oriented_streak": True,\n'
             f'                 "norm_type": "layernorm2d",\n'
             f'                 "full_res_norm_type": "affine_clamp",\n'
             f'                 "clamp_bound": 8.0,\n'
             f'                 "enc_clamp_stages": [3], "deep_clamp_bound": 32.0}},\n'
             f'          "config": "{OUT}",\n'
             f'          "desc": "{DESC}"}},\n')
    src = src.replace(anchor, entry + anchor)

    geo = '                "B0V3": W16_SIDD,'
    if src.count(geo) != 1:
        raise SystemExit("ARM_GEOMETRY anchor not unique")
    src = src.replace(geo, f'                "{ARM}": W16_SIDD,\n' + geo)
    tp.write_text(src, encoding="utf-8")
    print(f"registered {ARM}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
