"""Create the S3.3 arms: plain-k11 control, oriented, oriented+middle.

All three are identical to B0V3-KD-FEAT in every respect except the block --
same KD, same data, same 90k cosine schedule, same seed -- so each comparison
moves exactly one variable:

    B0V3-KD-FEAT     no block               (already trained, 90k)  <- control A
    B0V3-KD-K11      plain 11x11 depthwise  <- control B (receptive field)
    B0V3-KD-ORI      oriented block         <- treatment
    B0V3-KD-ORI-MID  oriented + middle      <- placement

A minus B isolates receptive field; B minus C isolates ORIENTATION at matched
receptive field and matched deployed cost. Without control B a win is
unattributable, which is why the plan's original three-arm S3.3 was not enough.

Validation stays the standard BSD68 / Rain100L / SOTS-clean trio so these arms
remain directly comparable to B0V3-KD-FEAT and so best.pth selection is
unchanged. The off-axis rain sets are scored afterwards, post hoc, exactly like
rescore_clean.py -- they are the discriminating measurement, not a training
signal.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BASE_CFG = Path("configs/train/b0v3_kd_feat.yaml")

ARMS = {
    "B0V3-KD-K11": dict(
        cfg="configs/train/b0v3_kd_k11.yaml",
        variant="plain", middle=False,
        desc="B0V3-KD-FEAT + plain 11x11 depthwise block (S3.3 receptive-field CONTROL)"),
    "B0V3-KD-ORI": dict(
        cfg="configs/train/b0v3_kd_ori.yaml",
        variant="oriented", middle=False,
        desc="B0V3-KD-FEAT + reparameterizable oriented block, decoder stages (S3.3)"),
    "B0V3-KD-ORI-MID": dict(
        cfg="configs/train/b0v3_kd_ori_mid.yaml",
        variant="oriented", middle=True,
        desc="B0V3-KD-FEAT + oriented block, decoder + middle (S3.3 placement)"),
}

MODEL_EXTRA = """  use_reparam_oriented: true
  reparam_k: 11
  reparam_variant: {variant}
  reparam_middle: {middle}
"""


def main() -> int:
    base = BASE_CFG.read_text(encoding="utf-8")

    for arm, spec in ARMS.items():
        out = Path(spec["cfg"])
        txt = base
        # append the block flags to the model: section (ends at the next
        # top-level key)
        # model kwargs live under `arch:` in this repo's configs, not `model:`
        # (`model:` is a path to configs/model/nafnet_locked.yaml)
        m = re.search(r"(?m)^arch:\n((?:[ \t].*\n)*)", txt)
        if not m:
            raise SystemExit("could not locate arch: section")
        block = m.group(1).rstrip("\n") + "\n" + MODEL_EXTRA.format(
            variant=spec["variant"], middle=str(spec["middle"]).lower())
        txt = txt[:m.start(1)] + block + txt[m.end(1):]
        txt = ("# S3.3 arm, generated by scripts/make_s33_arms.py.\n"
               f"# {spec['desc']}\n"
               "# Identical to b0v3_kd_feat.yaml except the block flags below.\n"
               + txt)
        out.write_text(txt, encoding="utf-8")
        print(f"wrote {out}")

    # ---- register in train.py -----------------------------------------
    tp = Path("src/train/train.py")
    src = tp.read_text(encoding="utf-8")
    if "B0V3-KD-ORI" in src:
        print("arms already registered")
        return 0

    anchor = '    "B0V3M": {"norm": {"arch": "student_v3",'
    if src.count(anchor) != 1:
        raise SystemExit("ARMS anchor not unique")
    entries = []
    for arm, spec in ARMS.items():
        entries.append(
            f'    # S3.3: {spec["desc"]}\n'
            f'    "{arm}": {{"norm": {{"arch": "student_v3",\n'
            f'                     "use_dcp_prior": True,\n'
            f'                     "use_strip_pool": True,\n'
            f'                     "use_oriented_streak": True,\n'
            f'                     "use_reparam_oriented": True,\n'
            f'                     "reparam_k": 11,\n'
            f'                     "reparam_variant": "{spec["variant"]}",\n'
            f'                     "reparam_middle": {spec["middle"]},\n'
            f'                     "norm_type": "layernorm2d",\n'
            f'                     "full_res_norm_type": "affine_clamp",\n'
            f'                     "clamp_bound": 8.0,\n'
            f'                     "enc_clamp_stages": [3], "deep_clamp_bound": 32.0}},\n'
            f'              "config": "{spec["cfg"]}",\n'
            f'              "desc": "{spec["desc"]}"}},\n')
    src = src.replace(anchor, "".join(entries) + anchor)

    geo_anchor = '                "B0V3M": W16_SIDD,'
    if src.count(geo_anchor) != 1:
        raise SystemExit("ARM_GEOMETRY anchor not unique")
    src = src.replace(
        geo_anchor,
        "".join(f'                "{a}": W16_SIDD,\n' for a in ARMS) + geo_anchor)

    tp.write_text(src, encoding="utf-8")
    print(f"registered {len(ARMS)} arms in src/train/train.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
